### ISSUE TITLE
Include more information when YAML parse exception occurs

### ISSUE THREAD

**Issue by macgregor** [alechenninger/monarch#34]
Had a random tab creep into a changeset and got the following error:
Exception in thread "main" while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 19, column 1:

```
^

at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420)
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:84)
at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:104)
at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:471)
at io.github.alechenninger.monarch.YamlMonarchParser.parseChanges(YamlMonarchParser.java:53)
at io.github.alechenninger.monarch.MonarchOptionsFromInputs.lambda$changes$5(MonarchOptionsFromInputs.java:73)
at java.util.Optional.map(Optional.java:215)
at io.github.alechenninger.monarch.MonarchOptionsFromInputs.changes(MonarchOptionsFromInputs.java:69)
at io.github.alechenninger.monarch.OverridableOptions$1.<init>(OverridableOptions.java:54)
at io.github.alechenninger.monarch.OverridableOptions.lambda$changes$11(OverridableOptions.java:53)
at io.github.alechenninger.monarch.Main.run(Main.java:89)
at io.github.alechenninger.monarch.Main.main(Main.java:179)
```

The tab was at the beginning of a blank line. I could see it being expected behavior but was definitely annoying. Could at least throw a better exception message (even just including the offending filename would be a big help)

**Comment by alechenninger** [comment]
Hrm I see. I guess tab is illegal character in YAML. In monarch I think we should catch any yaml parse exception and rethrow it with the filename as you have suggested. Thanks for the report!
